apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weamind
  namespace: weamind
spec:
  ingressClassName: traefik
  rules:
    - host: k8s.kyomind.tw
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weamind-line-bot
                port:
                  number: 80
